language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

sudo: false

os:
- linux
- osx

before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r shared/target/site/jacoco/jacoco.xml --partial
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r client/target/site/jacoco/jacoco.xml --partial
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r server/target/site/jacoco/jacoco.xml --partial
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar final