language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

sudo: required

os:
- linux
- osx

before_install:
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar

after_success:
- mvn org.jacoco:jacoco-maven-plugin:0.8.2:report
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r shared/target/site/jacoco/jacoco.xml --partial
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r client/target/site/jacoco/jacoco.xml --partial
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r server/target/site/jacoco/jacoco.xml --partial
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
- echo done